version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    container_name: mc
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "PURPUR"
    volumes:
      - ./plugins:/plugins
      - ./mods:/mods
      - ./config:/config
      - ./data:/data
