version: "3.8"

services:
  server:
    image: itzg/minecraft-server
    container_name: server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "PURPUR"
      ALLOW_NETHER: "false"
      ONLINE_MODE: "true"
      # OPS: |
      #   viasnake
      VERSION: "1.20.1"
    volumes:
      - ./server:/data
